name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the branch you want to build from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2  # Updated to use setup-node@v2
      with:
        node-version: '16'  # Updated to Node.js version 16 which is compatible with your package

    - name: Install and Build ğŸ”§
      run: |
        npm config set ignore-scripts true  # Ignore scripts that only need to run in a local development environment
        npm install --production --legacy-peer-deps --no-optional  # Updated to not install optional dependencies like fsevents
        npm run build  # Build your site

    - name: Deploy to GitHub Pages ğŸš€
      uses: JamesIves/github-pages-deploy-action@v4  # Updated to use the latest version v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Changed from GH_TOKEN to GITHUB_TOKEN
        branch: gh-pages  # The branch the action should deploy to.
        folder: dist  # The folder the action should deploy.
        clean: true  # Automatically remove deleted files from the deployment branch